# Configuration file for trinag model and hyperparameter settings
# of crop and weed dataset

#'0,1,2,3'
gpus_to_use: '0,1'
DPI: 300
LOG_WANDB: True

project_name: 'torchSegmentation'
experiment_name: 'droppath_layerscale_aug_focal'

log_directory: "/home/user01/data/talha/cityscape/logs/"
checkpoint_path: "/home/user01/data/talha/cityscape/chkpts/"


# Data loader parameters

data_dir: "/home/user01/data/talha/cityscape/data/"
# add sub dirs inside of train/val and test
sub_directories: ['images/images/', 'masks/masks/']
Normalize_data: True
Shuffle_data: True
# only for training data
Augment_data: True
pin_memory: True
num_workers: 6
num_classes: 20
img_height: 1024
img_width: 2048
# 4 means output of network is 4 times downsampled
output_stride: 4
input_channels: 3
label_smoothing: 0.0
batch_size: 8
WEIGHT_DECAY: 0.00005
# Regularization
stochastic_drop_path: 0.5
layer_scaling_val: 1e-2

# learning rate
learning_rate: 0.001
lr_schedule: 'cos'
epochs: 250 
warmup_epochs: 3
# one of 'batch_norm' or 'sync_bn' or 'layer_norm'
norm_typ: 'sync_bn'
BN_MOM: 0.9
SyncBN_MOM: 3e-4
# Hamburger Parameters
ham_channels: 512
put_cheese: True

DUAL: False
SPATIAL: TRUE
RAND_INIT: True

MD_S: 1
MD_D: 512
MD_R: 64

TRAIN_STEPS: 6
EVAL_STEPS: 6

INV_T: 1
BETA: 0.1
Eta: 0.9